### PR TITLE
Remove Level from /$metadata

### PR DESCRIPTION
**Pull request by sebbader-sap**
Solves #249

### CODE REVIEW

**Review by BirgitBoss — CHANGES_REQUESTED** [review]
It seems to me that https://app.swaggerhub.com/apis/Plattform_i40/SubmodelServiceSpecification/V3.0.2_SSP-001#/Submodel%20API/PatchSubmodelElementByPath-Metadata still has Level as parameter

**Comment by sebbader-sap** [comment]
SwaggerHub is not synched yet. Will do after this and a few other OpenAPI-related PRs are merged.

**Comment by BirgitBoss** [comment]
> SwaggerHub is not synched yet. Will do after this and a few other OpenAPI-related PRs are merged.

same for .yml I would say

**Comment by mjacoby** [comment]
@BirgitBoss I just did a detailed review and could not find anything wrong in the *.yaml files. If you still think there is something wrong, please provide an inline comment at the concrete position, otherwise update your review to "accept" so that @sebbader-sap can merge

**Review by BirgitBoss — APPROVED** [review]
did not find any errors

**Pull request merged**
