### PR TITLE
Files from the V3.0 Release

### PR DESCRIPTION
**Pull request by sebbader-sap**
This PR cleans up our mess from the - then private - Release 3.0 which now needs to be part of `main` and not hidden in another branch.
@Reviewers: only one of you is required, nevertheless, first one reviewing wins another review request :-).

### CODE REVIEW

**Comment by sebbader-sap** [comment]
Please don't merge directly even after an approval, we need to squash first.

**Comment by g1zzm0** [comment]
SubmodelServiceSpecification and DINSPEC16593-Schemas are missing

**Review by g1zzm0 — CHANGES_REQUESTED** [review]
- [x] Checked deleted files if they are old or outdated
- [ ] Checked new files if they are up-to-date and in syc with swagger files
- [x] Checked updated files if they are syc with swagger files
- [ ] Updated references nad names of APIs in readme.md according to GitHub and 

I think it's necessary to add DINSPEC16593-Schemas.
The other files looks good to me.

**Comment by sebbader-sap** [comment]
- [ ] reintroduce DINSPEC16593 OpenAPI file for this branch

**Comment by g1zzm0** [comment]
Reintroduce DINSPEC16593-Schemas

These files are out of date. The publication of the DINSPEC16593 schemas never happened officially. 
The mirror standard in Part II DINSPEC16593 schemas is therefore obsolete. 
The specification of the ProtocolInformation is defined in Part2 API schemas.

- [x] Checked deleted files if they are old or outdated
- [x] Checked new files if they are up-to-date and in syc with swagger files
- [x] Checked updated files if they are syc with swagger files
- [x] Updated references and names of APIs in readme.md according to GitHub and SwaggerHub
- [x] Mark DINSPEC16593 deprecated

**Review by g1zzm0 — APPROVED** [review]
Looks good to me.
All files are in sync with the resealed 3.0 version.
DINSPEC16593-Schemas Domain marked Deprecated

**Review by g1zzm0 — APPROVED** [review]
Note of obsolescence in DINSPEC in YAML file.

**Pull request merged**
