### PR TITLE
Fix ValueOnly

### PR DESCRIPTION
**Pull request by sebbader-sap**
Solves #251

### CODE REVIEW

**Review by BirgitBoss — APPROVED** [review]
I am not sure whether Schema ValueOnly is correct: empty means any object?

**Comment by sebbader-sap** [comment]
Yes, "empty" in terms of "no further JSON properties specified" still means that `type: object` holds. Which means indeed "any object", e.g., in contrast to a JSON Array.

**Comment by BirgitBoss** [comment]
#254

**Comment by g1zzm0** [comment]
Closes #251

**Pull request merged**
